<jsp:useBean id="global" class="ezc.ezbasicutil.EzGlobal" scope="session" />
<%
	HashMap cgHMRB = new HashMap();
			
	cgHMRB.put("AM","AOR, Menards");
	cgHMRB.put("AU","AOR");
	cgHMRB.put("BA","CS & AOR, Menards");
	cgHMRB.put("BB","CS & AOR");
	cgHMRB.put("BC","CS & CANADA AOR");
	cgHMRB.put("BD","CS & CANADA COSTCO");
	cgHMRB.put("BE","CS & CANADA THD");
	cgHMRB.put("BF","CS & MEXICO THD");
	cgHMRB.put("BG","CS & HOME DEPOT US");
	cgHMRB.put("BH","CS & CANADA LOWES");
	cgHMRB.put("BI","CS & MEXICO LOWES");
	cgHMRB.put("BJ","CS & Lowes, AOR");
	cgHMRB.put("BK","CS & LOWES US");
	cgHMRB.put("BL","CS & Menards, Trade");
	cgHMRB.put("BM","CS & MENARDS US");
	cgHMRB.put("BN","CS & CANADA RONA");
	cgHMRB.put("BO","CS & HD Lowes Menard");
	cgHMRB.put("BP","CS & AOR SAMS CLUB");
	cgHMRB.put("BQ","CS & RETAIL ONLY");
	cgHMRB.put("CA","CANADA AOR");
	cgHMRB.put("CC","CANADA COSTCO");
	cgHMRB.put("CS","CUSTOM SKU");
	cgHMRB.put("CT","CARTONS");
	cgHMRB.put("EI","E-TAIL/INTERNET");
	cgHMRB.put("FI","FIAT");
	cgHMRB.put("FG","FERGUSON EXCL..");
	cgHMRB.put("GE","GRAINGER EXCLUSIVE");
	cgHMRB.put("HC","CANADA THD");
	cgHMRB.put("HM","MEXICO THD");
	cgHMRB.put("HU","HOME DEPOT US");
	cgHMRB.put("LC","CANADA LOWES");
	cgHMRB.put("LM","MEXICO LOWES");
	cgHMRB.put("LR","Lowes, AOR");
	cgHMRB.put("LU","LOWES US");
	cgHMRB.put("MT","Menards, Trade");
	cgHMRB.put("MU","MENARDS US");
	cgHMRB.put("PF","FIXTURE PODS");
	//cgHMRB.put("QS","QUICK SHIP FAUCET");
	cgHMRB.put("RC","CANADA RONA");
	cgHMRB.put("RE","HD, Lowes, Menards");
	cgHMRB.put("SC","AOR SAMS CLUB");
	cgHMRB.put("ST","SAFETY TUB");
	cgHMRB.put("WB","WOLSELEY,BUILD.COM");
	cgHMRB.put("WW","WATERWORKS US");
	cgHMRB.put("ZR","RETAIL ONLY");
	cgHMRB.put("ZE","SEE Z_CUST_EXCL TBL");
	cgHMRB.put("ZS","HD,YOW");
	cgHMRB.put("ZT","LOWES,TRUMBULL");
	cgHMRB.put("ZU","HD,YOW,LOWES,TRUMBUL");
	cgHMRB.put("ZW","HD/YOW AOR LOWE/TRUM");
	cgHMRB.put("ZX","HD,YOW, AOR, ETAIL");
	cgHMRB.put("ZY","HD, YOW, AOR, FD");
	cgHMRB.put("ZZ","RETAIL, ETAIL ONLY");
	cgHMRB.put("MF","Fixture Modification");
	cgHMRB.put("FM","Faucet Modification");
	cgHMRB.put("FP","Faucet PODS");
	cgHMRB.put("TT","Trade & Trumbull Exclusive (for fittings)");
	cgHMRB.put("TR","Trade, YOW & Trumbull Exclusive");
	cgHMRB.put("TY","Trade & YOW Exclusive (for fittings)");
%>