
<script language="JavaScript">
<!--
function reloadPage(){
  document.forms[0].action = document.location;
  document.forms[0].submit();
}
//-->
</script>
<%
//String country=retinfo.getFieldValueString(0,BP_COUNTRY);
	String[][] countryList = {{"United States of America",	"USA"},
{"Canada",	"CAN"},
{"India",	"IND"},
{"Afghanistan",	"AFG"},
{"Albania",	"ALB"},
{"Algeria",	"DZA"},
{"American Samoa",	"ASM"},
{"Andorra",	"AND"},
{"Angola",	"AGO"},
{"Anguilla",	"AIA"},
{"Antarctica",	"ATA"},
{"Antigua and Barbuda",	"ATG"},
{"Argentina",	"ARG"},
{"Armenia",	"ARM"},
{"Aruba",	"ABW"},
{"Australia",	"AUS"},
{"Austria",	"AUT"},
{"Azerbaijan",	"AZE"},
{"Bahamas",	"BHS"},
{"Bahrain",	"BHR"},
{"Bangladesh",	"BGD"},
{"Barbados",	"BRB"},
{"Belarus",	"BLR"},
{"Belgium",	"BEL"},
{"Belize",	"BLZ"},
{"Benin",	"BEN"},
{"Bermuda",	"BMU"},
{"Bhutan",	"BTN"},
{"Bolivia",	"BOL"},
{"Botswana",	"BWA"},
{"Bouvet Island",	"BVT"},
{"Brazil",	"BRA"},
{"Brunei Darussalam",	"BRN"},
{"Bulgaria",	"BGR"},
{"Burkina Faso",	"BFA"},
{"Burundi",	"BDI"},
{"Cambodia",	"KHM"},
{"Cameroon",	"CMR"},
{"Cape Verde",	"CPV"},
{"Cayman Islands",	"CYM"},
{"Chad",	"TCD"},
{"Chile",	"CHL"},
{"China",	"CHN"},
{"Christmas Island",	"CXR"},
{"Colombia",	"COL"},
{"Comoros",	"COM"},
{"Congo",	"COG"},
{"Cook Islands",	"COK"},
{"Costa Rica",	"CRI"},
{"Cote Divoire",	"CIV"},
{"Croatia",	"HRV"},
{"Cuba",	"CUB"},
{"Cyprus",	"CYP"},
{"Czech Republic",	"CZE"},
{"Denmark",	"DNK"},
{"Djibouti",	"DJID"},
{"Dominica",	"DMA"},
{"Dominican Republic",	"DOM"},
{"East Timor",	"TMP"},
{"Ecuador",	"ECU"},
{"Egypt",	"EGY"},
{"El Salvador",	"SLV"},
{"Equatorial Guinea",	"GNQ"},
{"Eritrea",	"ERI"},
{"Estonia",	"EST"},
{"Ethiopia",	"ETH"},
{"Falkland Islands",	"FLK"},
{"Faroe Islands",	"FRO"},
{"iji",	"FJIF"},
{"Finland",	"FIN"},
{"France",	"FRA"},
{"France, Metropolitan",	"FXX"},
{"French Guiana",	"GUF"},
{"French Polynesia",	"PYF"},
{"Gabon",	"GAB"},
{"Gambia",	"GMB"},
{"Georgia",	"GEO"},
{"Germany",	"DEU"},
{"Ghana",	"GHA"},
{"Gibraltar",	"GIB"},
{"Greece",	"GRC"},
{"Greenland",	"GRL"},
{"Grenada",	"GRD"},
{"Guadeloupe",	"GLP"},
{"Guam",	"GUM"},
{"Guatemala",	"GTM"},
{"Guinea",	"GIN"},
{"Guinea-Bissau",	"GNB"},
{"Guyana",	"GUY"},
{"Haiti",	"HTI"},
{"Honduras",	"HND"},
{"Hong Kong",	"HKG"},
{"Hungary",	"HUN"},
{"Iceland",	"ISL"},
{"Indonesia",	"IDN"},
{"Iran",	"IRN"},
{"Iraq",	"IRQ"},
{"Ireland",	"IRL"},
{"Israel",	"ISR"},
{"Italy",	"ITA"},
{"Jamaica",	"JAM"},
{"Japan",	"JPN"},
{"Jordan",	"JOR"},
{"Kazakhstan",	"KAZ"},
{"Kenya",	"KEN"},
{"Kiribati",	"KIR"},
{"Korea",	"PRK"},
{"Kuwait",	"KWT"},
{"Kyrgyzstan",	"KGZ"},
{"Latvia",	"LVA"},
{"Lebanon",	"LBN"},
{"Lesotho",	"LSO"},
{"Liberia",	"LBR"},
{"Libyan Arab Jamahiriya",	"LBY"},
{"Liechtenstein",	"LIE"},
{"Lithuania",	"LTU"},
{"Luxembourg",	"LUX"},
{"Madagascar",	"MDG"},
{"Malawi",	"MWI"},
{"Malaysia",	"MYS"},
{"Maldives",	"MDV"},
{"Mali",	"MLI"},
{"Malta",	"MLT"},
{"Marshall Islands",	"MHL"},
{"Martinique",	"MTQ"},
{"Mauritania",	"MRT"},
{"Mauritius",	"MUS"},
{"Mayotte",	"MYT"},
{"Mexico",	"MEX"},
{"Micronesia",	"FSM"},
{"Moldova",	"MDA"},
{"Monaco",	"MCO"},
{"Mongolia",	"MNG"},
{"Montserrat",	"MSR"},
{"Morocco",	"MAR"},
{"Mozambique",	"MOZ"},
{"Myanmar",	"MMR"},
{"Namibia",	"NAM"},
{"Nauru",	"NRU"},
{"Nepal",	"NPL"},
{"Netherlands",	"NLD"},
{"Netherlands Antilles",	"ANT"},
{"New Caledonia",	"NCL"},
{"New Zealand",	"NZL"},
{"Nicaragua",	"NIC"},
{"Niger",	"NER"},
{"Nigeria",	"NGA"},
{"Niue",	"NIU"},
{"Norfolk Island",	"NFK"},
{"Northern Mariana Islands",	"MNP"},
{"Norway",	"NOR"},
{"Oman",	"OMN"},
{"Pakistan",	"PAK"},
{"Palau",	"PLW"},
{"Panama",	"PAN"},
{"Papua New Guinea",	"PNG"},
{"Paraguay",	"PRY"},
{"Peru",	"PER"},
{"Philippines",	"PHL"},
{"Pitcairn",	"PCN"},
{"Poland",	"POL"},
{"Portugal",	"PRT"},
{"Puerto Rico",	"PRI"},
{"Qatar",	"QAT"},
{"Reunion",	"REU"},
{"Romania",	"ROM"},
{"Russian Federation",	"RUS"},
{"Rwanda",	"RWA"},
{"Saint Lucia",	"LCA"},
{"Samoa",	"WSM"},
{"San Marino",	"SMR"},
{"Saudi Arabia",	"SAU"},
{"Senegal",	"SEN"},
{"Seychelles",	"SYC"},
{"Sierra Leone",	"SLE"},
{"Singapore",	"SGP"},
{"Slovakia",	"SVK"},
{"Slovenia",	"SVN"},
{"Solomon Islands",	"SLB"},
{"Somalia",	"SOM"},
{"South Africa",	"ZAF"},
{"Spain",	"ESP"},
{"Sri Lanka",	"LKA"},
{"St. Helena",	"SHN"},
{"Sudan",	"SDN"},
{"Suriname",	"SUR"},
{"Swaziland",	"SWZ"},
{"Sweden",	"SWE"},
{"Switzerland",	"CHE"},
{"Syria",	"SYR"},
{"Taiwan",	"TWN"},
{"Tajikistan",	"TJK"},
{"Tanzania",	"TZA"},
{"Thailand",	"THA"},
{"Togo",	"TGO"},
{"Tokelau",	"TKL"},
{"Tonga",	"TON"},
{"Trinidad and Tobago",	"TTO"},
{"Tunisia",	"TUN"},
{"Turkey",	"TUR"},
{"Turkmenistan",	"TKM"},
{"Tuvalu",	"TUV"},
{"Uganda",	"UGA"},
{"Ukraine",	"UKR"},
{"United Arab Emirates",	"ARE"},
{"United Kingdom",	"GBR"},
{"Uruguay",	"URY"},
{"Uzbekistan",	"UZB"},
{"Vanuatu",	"VUT"},
{"Vatican City",	"VAT"},
{"Venezuela",	"VEN"},
{"Viet Nam",	"VNM"},
{"Western Sahara",	"ESH"},
{"Yemen",	"YEM"},
{"Yugoslavia",	"YUG"},
{"Zaire",	"ZAR"},
{"Zambia",	"ZMB"},
{"Zimbabwe",	"ZWE"}};

%>
<select name="Country" onChange="reloadPage()">
	<% 
		String sel = "";
		for (int i=0;i<countryList.length;i++) {
			sel = "";
			if (country.equals(countryList[i][1])) sel = " selected";%>
			<Option value="<%=countryList[i][1]%>" <%=sel%>><%=countryList[i][0]%>
		<%
		}
	%>
</SELECT>
