<%
String[] stateListUSA ={"Alabama",
"Alaska",
"Alberta",
"American Samoa",
"Arizona",
"Arkansas",
"Armed Forces Americas",
"Armed Forces Europe",
"Armed Forces Pacific",
"British Columbia",
"California",
"Colorado",
"Connecticut",
"Delaware",
"District Of Columbia",
"Florida",
"Georgia",
"Guam",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Manitoba",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Brunswick",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"Newfoundland",
"North Carolina",
"North Dakota",
"Northern Mariana Is",
"Northwest Territories",
"Nova Scotia",
"Ohio",
"Oklahoma",
"Ontario",
"Oregon",
"Palau",
"Pennsylvania",
"Prince Edward Island",
"Province du Quebec",
"Puerto Rico",
"Rhode Island",
"Saskatchewan",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virgin Islands",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming",
"Yukon Territory"};

%>
<SELECT NAME="State">
<%
for (int i=0;i<stateListUSA.length;i++){
	stsel="";
	if (state.equals(stateListUSA[i])) stsel=" selected";
	%>
	<OPTION VALUE="<%=stateListUSA[i]%>" <%=stsel%>><%=stateListUSA[i]%>
	<%
}
%>
</SELECT>
<input type="hidden" name="maxZip" value="5">