 <SELECT NAME="State">
                      <OPTION value="AL">Alabama 
                      <OPTION value="AK">Alaska 
                      <OPTION value="AB">Alberta 
                      <OPTION value="AS">American Samoa 
                      <OPTION value="AZ">Arizona 
                      <OPTION value="AR">Arkansas 
                      <OPTION value="AA">Armed Forces Americas 
                      <OPTION value="AE">Armed Forces Europe 
                      <OPTION value="AP">Armed Forces Pacific 
                      <OPTION value="BC">British Columbia 
                      <OPTION value="CA">California 
                      <OPTION value="CO">Colorado 
                      <OPTION value="CT">Connecticut 
                      <OPTION value="DE">Delaware 
                      <OPTION value="DC">District Of Columbia 
                      <OPTION value="FL">Florida 
                      <OPTION value="GA">Georgia 
                      <OPTION value="GU">Guam 
                      <OPTION value="HI">Hawaii 
                      <OPTION value="ID">Idaho 
                      <OPTION value="IL">Illinois 
                      <OPTION value="IN">Indiana 
                      <OPTION value="IA">Iowa 
                      <OPTION value="KS">Kansas 
                      <OPTION value="KY">Kentucky 
                      <OPTION value="LA">Louisiana 
                      <OPTION value="ME">Maine 
                      <OPTION value="MB">Manitoba 
                      <OPTION value="MD">Maryland 
                      <OPTION value="MA">Massachusetts 
                      <OPTION value="MI">Michigan 
                      <OPTION value="MN">Minnesota 
                      <OPTION value="MS">Mississippi 
                      <OPTION value="MO">Missouri 
                      <OPTION value="MT">Montana 
                      <OPTION value="NE">Nebraska 
                      <OPTION value="NV">Nevada 
                      <OPTION value="NB">New Brunswick 
                      <OPTION value="NH">New Hampshire 
                      <OPTION value="NJ">New Jersey 
                      <OPTION value="NM">New Mexico 
                      <OPTION value="NY">New York 
                      <OPTION value="NF">Newfoundland 
                      <OPTION value="NC">North Carolina 
                      <OPTION value="ND">North Dakota 
                      <OPTION value="MP">Northern Mariana Is 
                      <OPTION value="NT">Northwest Territories 
                      <OPTION value="NS">Nova Scotia 
                      <OPTION value="OH">Ohio 
                      <OPTION value="OK">Oklahoma 
                      <OPTION value="ON">Ontario 
                      <OPTION value="OR">Oregon 
                      <OPTION value="PW">Palau 
                      <OPTION value="PA">Pennsylvania 
                      <OPTION value="PE">Prince Edward Island 
                      <OPTION value="PQ">Province du Quebec 
                      <OPTION value="PR">Puerto Rico 
                      <OPTION value="RI">Rhode Island 
                      <OPTION value="SK">Saskatchewan 
                      <OPTION value="SC">South Carolina 
                      <OPTION value="SD">South Dakota 
                      <OPTION value="TN">Tennessee 
                      <OPTION value="TX">Texas 
                      <OPTION value="UT">Utah 
                      <OPTION value="VT">Vermont 
                      <OPTION value="VI">Virgin Islands 
                      <OPTION value="VA">Virginia 
                      <OPTION value="WA">Washington 
                      <OPTION value="WV">West Virginia 
                      <OPTION value="WI">Wisconsin 
                      <OPTION value="WY">Wyoming 
                      <OPTION value="YT">Yukon Territory 
                    </SELECT>