<!--	######################################################################
 
		Generated By EzWorkbench On Sunday,August 18,2002 At 11:38
 
	######################################################################	-->
 
<jsp:useBean id="Session" class="ezc.session.EzSession" scope="session" />
<jsp:useBean id="EzWorkFlowManager" class="ezc.ezworkflow.client.EzWorkFlowManager" scope="session" />
<%@ page import="ezc.ezparam.ReturnObjFromRetrieve,ezc.ezparam.*,ezc.ezworkflow.params.*" %>
<%!
	//This generic function is to remove null from string
	public Object removeNull(Object val)
	{
		if(val==null || "null".equals(val))
			return "";
		else
			return val;
		}
%>
