			
			
			
			
			
			
			
			
<%			
  String PoTypes[][] = {  	
					
				{"DB" ,"DB-->Dummy purchase order" },
				{"FO" ,"FO-->Framework order"},
				{"NB" ,"NB-->RM/PM/Spares Dom. PO"},
				{"UB" ,"UB-->Stock transport ord."},
				{"ZAL","ZAL-->STO EX MFG-2 STEP AL"},
				{"ZBB","ZBB-->STO EX MRKTING PLANT" },
				{"ZCPD","ZCPD-->Cap Gds Domestic PO"},
				{"ZCPI","ZCPI-->Cap Gds Import PO"},
				{"ZCPX","ZCPX-->Cap Gds Domestic PO"},
				{"ZFGD","ZFGD-->Trading/FG PO"},
				{"ZFGI","ZFGI-->Trading Imports PO"},
				{"ZICC","ZICC-->Interco Transfers"},
				{"ZLFG","ZLFG-->STO EX LL MFG. PLANT"},
				{"ZLRM","ZLRM-->STO RM/PM/SFG TO LL"},
				{"ZNLL","ZNLL-->Non SAP LL PO"},
				{"ZPP",	"ZPP-->STO EX MFG PLANT"},
				{"ZPP2","ZPP2-->STO EX MFG PLANT SCC"},
				{"ZRFI","ZRFI-->RFCL Import FG PO"},
				{"ZRMI","ZRMI-->RM/PM IMPORT PO"},
				{"ZRUS","ZRUS-->STO-CONSIGNMENT SALE"},
				{"ZRXL","ZRXL-->PO-Zero Value"},
				{"ZSAP","ZSAP-->PO FOR NONSAP LOCNS"},
				{"ZSC","ZSC-->Sub Contract PO"},
				{"ZSC2","ZSC2-->Sub Contract PO"},
				{"ZSER","ZSER-->Service PO"},
				{"ZSST","ZSST-->STO RM/PM/SFG SUB CC"},
				{"ZST","ZST-->STO Without Delivery"}
			    };
	String valuationTypes[] = {"01","02","A/L (SFG)","A/L FOR RM","C1","C2","C3","DOM. (SFG)","DOM.FOR RM","EIGEN","FREMD","LAND 1","LAND 2","MFD (FG)","MFD (SFG)","OGL (SFG)","OGL FOR RM","PROC (FG)","RAKTION","RM MOHALI","RM TOANSA","RNORMAL"};
	
	String confctrlKeys[][] = {
					{"0001","0001-->Domestic Confirm"},
					{"0002","0002-->Import Confirmation"},
					{"0003","0003-->Kandla Confirmation"},
					{"0004","0004-->Inbound delivery"},
					{"ZPLN","ZPLN-->Plng. Confirmations"}
				  };	
	
	
	String taxCodes[][] = {
	
				{"10","10-->vat for gb"},
				{"1G","1G-->MP VAT"},
				{"7F","7F-->Mumbai RFCL Tax"},
				{"A0","A0-->Zero Tax Code -- Input Tax"},
				{"A1","A1-->Chennai Food"},
				{"A2","A2-->Pondicherry Food"},
				{"A3","A3-->Secunderabad Food"},
				{"A4","A4-->Ernakulam Food"},
				{"A5","A5-->Bangalore Food"},
				{"A6","A6-->Calcutta Food"},
				{"A7","A7-->Patna Food"},
				{"A8","A8-->Guwahati Food"},
				{"A9","A9-->Nagaland Food"},

				{"AB","AB-->test"},
				{"AD","AD-->Input tax 100% No ED"},
				{"B1","B1-->Sikkim Food"},
				{"B2","B2-->Tripura Food"},
				{"B3","B3-->Meghalaya Food"},
				{"B4","B4-->Manipur Food"},
				{"B5","B5-->Arunachal Pradesh Food"},
				{"B6","B6-->Mumbai Food"},
				{"B7","B7-->Goa Food"},
				{"B8","B8-->Ahmedabad Food"},
				{"B9","B9-->Indore Food"},
				{"BA","BA-->LST 4%  No ED"},
				{"BF","BF-->LST 5.4% (4% LST+10 % Surcharge + 1% TOT on inv)"},
				{"BJ","BJ-->CST 1.0% against C form No ED"},
				{"BK","BK-->CST 2.0% against C form No ED"},
				{"BL","BL-->CST 3.0% against C form No ED"},
				{"BM","BM-->CST 4.0% against C form No ED"},
				{"C1","C1-->Ambala Food"},
				{"C2","C2-->Ghaziabad Food"},
				{"C3","C3-->Mohali food"},
				{"C4","C4-->Himachal Pradesh Food"},
				{"C5","C5-->Chandigarh Food"},
				{"C6","C6-->Jammu Food"},
				{"C7","C7-->Jaipur Food"},
				{"C8","C8-->Cuttack Food"},
				{"C9","C9-->New-Delhi Food"},
				{"D1","D1-->Katmandu Food"},
				{"D2","D2-->Chennai Medicines"},
				{"D3","D3-->Pondicherry - Mediciness"},
				{"D4","D4-->Secunderabad Medicines"},
				{"D5","D5-->Ernakulam Medicines"},
				{"D6","D6-->Bangalore Medicines"},
				{"D7","D7-->Calcutta Medicines"},
				{"D8","D8-->Patna Medicines"},
				{"D9","D9-->Guwahati Medicines"},
				{"DX","DX-->NO TAX.ED TO SETOFF"},
				{"E0","E0-->export taxes"},
				{"E1","E1-->Tax on exports"},
				{"EE","EE-->LST4.4%(4%tax+10%surcharge)InputTax100% EDtosetoff"},
				{"EG","EG-->LST4.6%(4% tax+15% surcharge)Inputtax100%EDtosetof"},
				{"F1","F1-->Nagaland - Medicines"},
				{"F2","F2-->Sikkim - Medicines"},
				{"F3","F3-->Tripura -Medicines"},
				{"F4","F4-->Meghalaya - Mediciness"},
				{"F5","F5-->Manipur -Medicines"},
				{"F6","F6-->Arunachal Pradesh - Medicines"},
				{"F7","F7-->Mumbai Medicines"},
				{"F8","F8-->Goa -Medicines"},
				{"F9","F9-->Ahmedabad Medicines"},
				{"FD","FD-->CST 2.0% agnst C form Input tax 100% ED to Setoff"},
				{"FE","FE-->CST 3.0% agnst C form Input tax 100% ED to Setoff"},
				{"FF","FF-->CST 4.0% agnst C form Input tax 100% ED to Setoff"},
				{"G1","G1-->Indore Medicines"},
				{"G2","G2-->Ambala Medicines"},
				{"G3","G3-->Ghaziabad Medicines"},
				{"G4","G4-->Mohali Medicines"},
				{"G5","G5-->Himachal Pradesh Medicines"},
				{"G6","G6-->Chandigarh Medicines"},
				{"G7","G7-->Jammu Medicines"},
				{"G8","G8-->Jaipur Medicines"},
				{"G9","G9-->Cuttack Medicines"},
				{"H1","H1-->New Delhi Medicines"},
				{"H2","H2-->Katmandu Medicines"},
				{"H3","H3-->APSRTC SALES TAX RATE IN AP"},
				{"H4","H4-->CHANDIGARH(SALES TO PUNJAB)"},
				{"I0","I0-->Input tax 100% No Excise Duty(Gate Pass)"},
				{"I1","I1-->Input tax 95%ED to setoff;5% to inventory"},
				{"I2","I2-->Input tax 100% ED to inventory"},
				{"I3","I3-->Input tax 100% ED to setoff"},
				{"J1","J1-->Mumbai API"},
				{"K1","K1-->Madurai Food"},
				{"K2","K2-->Madurai Medicines"},
				{"K3","K3-->Vijaywada Food"},
				{"K4","K4-->Vijaywada Medicines"},
				{"K5","K5-->Asansol Food"},
				{"K6","K6-->Asansol Medicines"},
				{"K7","K7-->Ranchi Food"},
				{"K8","K8-->Ranchi Medicines"},
				{"K9","K9-->Nagpur Food"},
				{"L1","L1-->Nagpur Medicines"},
				{"L2","L2-->Pune Food"},
				{"L3","L3-->Pune Medicines"},
				{"L4","L4-->Indore (VAT) Food"},
				{"L5","L5-->Indore (VAT) Medicines"},
				{"L6","L6-->Indore Injectible"},
				{"L8","L8-->Lucknow Food"},
				{"L9","L9-->Lucknow Medicines"},
				{"M1","M1-->Andaman Food"},
				{"M2","M2-->Andaman Medicines"},
				{"M3","M3-->Nil sales Tax"},
				{"M4","M4-->Sales Tax within Punjab"},
				{"M5","M5-->Tax Code for Dewas"},
				{"M6","M6-->Tax code for Paonta"},
				{"M7","M7-->tax code for Dewas scrap (drums) etc."},
				{"MM","MM-->test against AA"},
				{"N1","N1-->Domestic Trading-Delhi"},
				{"N2","N2-->Domestic Trading - Mumbai"},
				{"N3","N3-->Domestic Trading - Mohali"},
				{"V0","V0-->No excise no sales tax"},
				{"V1","V1-->Excise duty + LST"},
				{"V2","V2-->For CST 1% - for punjab from chandigarh sale"},
				{"V3","V3-->VAT 12.50%"},
				{"V4","V4-->Stock transfer"},
				{"V5","V5-->Excise duty + LST"},
				{"V6","V6-->Excise Duty and CST"},
				{"V7","V7-->Free supplies"},
				{"V8","V8-->Both LST and CST"},
				{"VX","VX-->test for ser tax"},
				{"VZ","VZ-->ser tax"},
				{"X1","X1-->Material specific for Mohali plant"},
				{"X2","X2-->Mohali plant w/o sales tax number"},
				{"X3","X3-->Scrap Sale-Paonta"},
				{"X4","X4-->Sales- Zero Tax Code"}
			};			
	
	
	
			
   String houseBankIds[][] = {			
			
			{"0"	,"0-->Dummy Bank(0)"},
			{"01-PC","01-PC-->PCI-Corpor(PCI-CORPOR)" },
			{"02-PC","02-PC-->PCI-MOI(PCI-MOI)	" },
			{"03-PC","03-PC-->PCI-DOMMKT(PCI-DOMMKT)" },
			{"04-PC","04-PC-->PCI-API DO(PCI-APIMOH)" },
			{"05-PC","05-PC-->PCI-APIPRO(PCI-APIPRO)" },
			{"06-PC","06-PC-->PCI-API MO(PCI-APIMOH)" },
			{"07-PC","07-PC-->PCI-API TO(PCI-APITOA)" },
			{"08-PC","08-PC-->PCI-PHARMA(PCI-PHARMA)" },
			{"09-PC","09-PC-->PCI-PHARMA(PCI-PHARMA)" },
			{"10-PC","10-PC-->PCI-INDORE(PCI-INDORE)" },
			{"11-PC","11-PC-->PCI-TOANSA(PCI-TOANSA)" },
			{"12-PC","12-PC-->PCI-MUMBAI(PCI-MUMBAI)" },
			{"18-PC","18-PC-->Petty Cash(18-PC)	" },
			{"19-PC","19-PC-->Petty Cash(19-PC)	" },
			{"ABMBA","ABMBA-->ABN Mum CA(ABN-CA2130)" },
			{"ABNDA","ABNDA-->ABN ND CA6(ABN-CA6058)" },
			{"ABNDB","ABNDB-->ABN ND CA6(ABN-CA6058)" },
			{"ABNDC","ABNDC-->ABN Amro B(ABN-STLOAN)" },
			{"ABNDD","ABNDD-->ABN Amro B(ABN-PC-RUP)" },
			{"ABNDE","ABNDE-->ABN Amro B(ABN-PCFC)	" },
			{"ABNDF","ABNDF-->ABN Amro B(ABN-FOBP-R)" },
			{"ABNDG","ABNDG-->ABN Amro B(ABN-FOBP-F)" },
			{"ABNDH","ABNDH-->ABN Amro B(ABN-FOBN-R)" },
			{"ABNDI","ABNDI-->ABN Amro B(ABN-FOBN-F)" },
			{"ABNDJ","ABNDJ-->ABN Amro B(ABN-EEFC)	" },
			{"ABNDK","ABNDK-->ABN Amro B(ABN-CRYST)	" },
			{"ABNDL","ABNDL-->ABN ND CA-(CA6298613)	" },
			{"ABROA","ABROA-->ABN AMRO B(2641-72059)" },
			{"ABROB","ABROB-->ABN AMRO R(2641-72059)" },
			{"ABRUA","ABRUA-->ABN AMRO C(4081481080)" },
			{"ABRUB","ABRUB-->ABN AMRO C(4080784504)" },
			{"ABRUC","ABRUC-->ABN AMRO C(044525217)	" },
			{"ABRUD","ABRUD-->ABN AMRO C(044525217)	" },
			{"ABRUE","ABRUE-->ABN AMRO B(044525217)	" },
			{"AMNDA","AMNDA-->AMEX ND CA(AMX-CA3103)" },
			{"AMNDB","AMNDB-->AMEX ND CA(AMX-CA3103)" },
			{"AMNDC","AMNDC-->American E(AMEX-STLOA)" },
			{"AMNDD","AMNDD-->American E(AMEX-PC-IN)" },
			{"AMNDE","AMNDE-->American E(AMEX-PCFC)	" },
			{"AMNDF","AMNDF-->American E(AMEX-FOBP-)" },
			{"AMNDG","AMNDG-->American E(AMEX-FOBP-)" },
			{"AMNDH","AMNDH-->American E(AMEX-FOBN-)" },
			{"AMNDI","AMNDI-->American E(AMEX-FOBN-)" },
			{"AMNDJ","AMNDJ-->American E(AMEX-EEFC)	" },
			{"AMNDK","AMNDK-->American E(AMEX-CRYST)" },
			{"AZBNA","AZBNA-->ANZGB BANG(CC834)	" },
			{"AZERA","AZERA-->ANZGB ERNA(CC324)	" },
			{"AZHYA","AZHYA-->ANZGB Hyd (CA1-CHC-11)" },
			{"AZHYB","AZHYB-->ANZGB ABID(CC991)	" },
			{"AZMBA","AZMBA-->ANZGB Mum (CA01CBC813)" },
			{"AZMBB","AZMBB-->ANZGB Mum (CA01CBC813)" },
			{"AZMBC","AZMBC-->ANZGB Mum (CA01CBC813)" },
			{"AZMBD","AZMBD-->ANZGB Mum (CA01CBC813)" },
			{"AZMBE","AZMBE-->ANZGB MUMB(CC217)	" },
			{"AZMDA","AZMDA-->ANZGB MADR(CC469)	" },
			{"AZNDA","AZNDA-->ANZ ND CA-(CA-2534932)" },
			{"AZNDB","AZNDB-->ANZGB ND C(CA01CHC607)" },
			{"AZNDC","AZNDC-->ANZ ND CA (CA-2534934)" },
			{"AZNDD","AZNDD-->ANZ ND CA-(CA-2534935)" },
			{"AZNDE","AZNDE-->ANZGB ND C(CA01CHC607)" },
			{"AZNDG","AZNDG-->ANZ Grindl(ANZ-STLOAN)" },
			{"AZNDH","AZNDH-->ANZ Grindl(ANZ-PC-INR)" },
			{"AZNDI","AZNDI-->ANZ Grindl(ANZ-PCFC)	" },
			{"AZNDJ","AZNDJ-->ANZ Grindl(ANZ-FOBP-I)" },
			{"AZNDK","AZNDK-->ANZ Grindl(ANZ-FOBP-F)" },
			{"AZNDL","AZNDL-->ANZ Grindl(ANZ-FOBN-R)" },
			{"AZNDM","AZNDM-->ANZ Grindl(ANZ-FOBN-F)" },
			{"AZNDN","AZNDN-->ANZ Grindl(ANZ-EEFC)	" },
			{"AZNDO","AZNDO-->ANZ Grindl(ANZ-CRYST)	" },
			{"AZNDP","AZNDP-->ANZ ND CA (ANZ-CA2534)" },
			{"AZNDQ","AZNDQ-->ANZ ND CA (CA25349373)" },
			{"AZNDR","AZNDR-->ANZGB ND C(CC340)	" },
			{"AZNDS","AZNDS-->ANZGB ND C(CC351)	" },
			{"BANDA","BANDA-->BOA ND CA7(CA706010)	" },
			{"BANDB","BANDB-->BOA ND CA3(CA33270017)" },
			{"BANDC","BANDC-->Bank of Am(BOA-STLOAN)" },
			{"BANDD","BANDD-->Bank of Am(BOA-PC-INR)" },
			{"BANDE","BANDE-->Bank of Am(BOA-PCFC)	" },
			{"BANDF","BANDF-->Bank of Am(BOA-FOBP-R)" },
			{"BANDG","BANDG-->Bank of Am(BOA-FOBP-F)" },
			{"BANDH","BANDH-->Bank of Am(BOA-FOBN-R)" },
			{"BANDI","BANDI-->Bank of Am(BOA-FOBN-F)" },
			{"BANDJ","BANDJ-->Bank of Am(BOA-EEFC)	" },
			{"BANDK","BANDK-->Bank of Am(BOA-CRYST)	" },
			{"BCNDA","BCNDA-->BARC ND CA(CA351881-2)" },
			{"BCNDB","BCNDB-->Barclays B(BARC-STLOA)" },
			{"BCNDC","BCNDC-->Barclays B(BARC-PC-RU)" },
			{"BCNDD","BCNDD-->Barclays B(BARC-PCFC)	" },
			{"BCNDE","BCNDE-->Barclays B(BARC-FOBP-)" },
			{"BCNDF","BCNDF-->Barclays B(BARC-FOBP-)" },
			{"BCNDG","BCNDG-->Barclays B(BARC-FOBN-)" },
			{"BCNDH","BCNDH-->Barclays B(FOBN-FORCU)" },
			{"BCNDI","BCNDI-->Barclays B(BARC-EEFC)	" },
			{"BCNDJ","BCNDJ-->Barclays B(BARC-CRYST)" },
			{"BNNDA","BNNDA-->BNP ND CA1(BNP-CA1012)" },
			{"CBMBA","CBMBA-->CANARA For(CANRA-CA-1)" },
			{"CBNDA","CBNDA-->CANARA ND (CANARA-CC1)" },
			{"CBNDB","CBNDB-->CANARA ND (CANARA-CC1)" },
			{"CBNDC","CBNDC-->CANARA ND (CANARA-CC1)" },
			{"CBNDD","CBNDD-->CANARA ND (CANARA-CCG)" },
			{"CBNDE","CBNDE-->CANARA BAN(CA-5289)	" },
			{"CIKZA","CIKZA-->Citi Bank,(3-45401)	" },
			{"CIKZB","CIKZB-->CITI BANK (3-45100)	" },
			{"CINDA","CINDA-->CITI ND CA(CITICA1128)" },
			{"CINDB","CINDB-->CITI ND CA(CITI-CA112)" },
			{"CINDC","CINDC-->CITI ND CA(CITI-CA112)" },
			{"CINDD","CINDD-->Citi Bank (CITI-STLOA)" },
			{"CINDE","CINDE-->Citi Bank (CITI-PC-RU)" },
			{"CINDF","CINDF-->Citi Bank (CITI-PCFC)	" },
			{"CINDG","CINDG-->Citi Bank (CITI-FOBP-)" },
			{"CINDH","CINDH-->Citi Bank (CITI-FOBP-)" },
			{"CINDI","CINDI-->Citi Bank (CITI-FOBN-)" },
			{"CINDJ","CINDJ-->Citi Bank (CITI-FOBN-)" },
			{"CINDK","CINDK-->Citi Bank (CITI-EEFC)	" },
			{"CINDL","CINDL-->Citi Bank (CITI-CRYST)" },
			{"CINDS","CINDS-->CITI BANK,(CA01128175)" },
			{"CLUAA","CLUAA-->Calyon ban(2600100217)" },
			{"CLUAB","CLUAB-->Calyon Ban(2600100217)" },
			{"CLVNA","CLVNA-->CALYON- Ba(2103121500)" },
			{"CLVNB","CLVNB-->CALYON- Ba(2103121500)" },
			{"CLYDA","CLYDA-->Calyon Cor(CA02203579)" },
			{"CLYDB","CLYDB-->CALYON BAN(CLY-EEFC)	" },
			{"CLYDC","CLYDC-->CALYON BAN(CA20357910)" },
			{"DCCDA","DCCDA-->DTSCH Chd (CA3004017-)" },
			{"DCCDB","DCCDB-->DTSCH Chd (CA3004017-)" },
			{"DCMBA","DCMBA-->DEUTSCHE M(CA-0000646)" },
			{"DCNDA","DCNDA-->DEUTSCHE N(CA10000-33)" },
			{"DCNDB","DCNDB-->DEUTSCHE N(CA10000-33)" },
			{"DCNDC","DCNDC-->Deustche B(DEUT-STLOA)" },
			{"DCNDD","DCNDD-->Deustche B(DEUT-PC-IN)" },
			{"DCNDE","DCNDE-->Deustche B(DEUT-PCFC)	" },
			{"DCNDF","DCNDF-->Deustche B(DEUT-FOBP-)" },
			{"DCNDG","DCNDG-->Deustche B(DEUT-FOBP-)" },
			{"DCNDH","DCNDH-->Deustche B(DEUT-FOBN-)" },
			{"DCNDI","DCNDI-->Deustche B(DEUT-FOBN-)" },
			{"DCNDJ","DCNDJ-->Deutsche B(DEUT-EEFC)	" },
			{"DCNDK","DCNDK-->Deustche B(DEUT-CRYST)" },
			{"DSMBA","DSMBA-->DBS Bank M(CA71046)	" },
			{"FDNDA","FDNDA-->FEDERAL ND(FEDERAL-CA)" },
			{"HDCDA","HDCDA-->RANBAXY LA(0350310000)" },
			{"HDGOA","HDGOA-->RANBAXY LA(CA16903100)" },
			{"HDINA","HDINA-->RANBAXY LA(CA03603100)" },
			{"HDMHA","HDMHA-->RANBAXY LA(0600310003)" },
			{"HDMHB","HDMHB-->RANBAXY LA(0600310003)" },
			{"HDMHC","HDMHC-->RANBAXY LA(5430310000)" },
			{"HDNDA","HDNDA-->HDFC ND CA(CA-0029587)" },
			{"HDNDB","HDNDB-->HDFC Bank( DFC-PC-RU)	" },
			{"HDNDC","HDNDC-->HDFC Bank( HDFC-PCFC)	" },
			{"HDNDD","HDNDD-->HDFC Bank( DFC-FOBP-)	" },
			{"HDNDE","HDNDE-->HDFC Bank( DFC-FOBP-)	" },
			{"HDNDF","HDNDF-->HDFC Bank( DFC-FOBN-)	" },
			{"HDNDG","HDNDG-->HDFC Bank( DFC-FOBN-)	" },
			{"HDNDH","HDNDH-->HDFC Bank( DFC-EEFC)	" },
			{"HDNDI","HDNDI-->HDFC Bank( DFC-CRYST)	" },
			{"HDNDJ","HDNDJ-->HDFC Bank( DFC-STLOA)	" },
			{"HDNDK","HDNDK-->HDFC Bank( DFC-IMLOA)	" },
			{"HDNDM","HDNDM-->	 (KGM)		" },
			{"HDNDO","HDNDO-->HDFC Bank (CA-0303100)" },
			{"HDNDP","HDNDP-->RANBAXY LA(0030310004)" },
			{"HDNDQ","HDNDQ-->RANBAXY LA(0030310004)" },
			{"HDNDR","HDNDR-->RANBAXY LA(0080310000)" },
			{"HDNDS","HDNDS-->RANBAXY LA(0080310000)" },
			{"HDNDT","HDNDT-->RANBAXY LA(CC00303100)" },
			{"HDNDU","HDNDU-->RANBAXY LA(CA00303100)" },
			{"HDNDV","HDNDV-->RANBAXY LA(0060310003)" },
			{"HDNDW","HDNDW-->RANBAXY LA(0060310003)" },
			{"HDNDX","HDNDX-->RANBAXY LA(0030310004)" },
			{"HDNDY","HDNDY-->RANBAXY LA(0030310004)" },
			{"HDPNA","HDPNA-->RANBAXY LA(CA00703100)" },
			{"HSCLA","HSCLA-->HSBC CALCU(CC-001)	" },
			{"HSMBA","HSMBA-->HSBC Mum C(CA00257743)" },
			{"HSNDA","HSNDA-->HSBC ND CA(CA05132734)" },
			{"HSNDB","HSNDB-->HSBC ND CA(CA51-31038)" },
			{"HSNDC","HSNDC-->HSBC ND CA(CA51-31038)" },
			{"HSNDD","HSNDD-->HSBC, New (HSBC-STLOA)" },
			{"HSNDE","HSNDE-->HSBC Limit(HSBC-PC-IN)" },
			{"HSNDF","HSNDF-->HSBC Limit(HSBC-PCFC)	" },
			{"HSNDG","HSNDG-->HSBC Limit(HSBC-FOBP-)" },
			{"HSNDH","HSNDH-->HSBC Limit(HSBC-FOBP-)" },
			{"HSNDI","HSNDI-->HSBC Limit(HSBC-FOBN-)" },
			{"HSNDJ","HSNDJ-->HSBC Limit(HSBC-FOBN-)" },
			{"HSNDK","HSNDK-->HSBC Limit(HSBC-EEFC)	" },
			{"HSNDL","HSNDL-->HSBC Limit(HSBC-CRYST)" },
			{"HSSGA","HSSGA-->HSBC, Sing(CA14121218)" },
			{"ISNDA","ISNDA-->INDUSIND B(CA-125300-)" },
			{"PNAHA","PNAHA-->PNB AHMEDA(CC-131)	" },
			{"PNAMA","PNAMA-->PNB AMBALA(CC-161)	" },
			{"PNASA","PNASA-->PNB ASANSO(CA1275)	" },
			{"PNBNA","PNBNA-->PNB BANGLO(CC-201)	" },
			{"PNCDA","PNCDA-->PNB Chd CC(PNB,CHD-CC)" },
			{"PNCDB","PNCDB-->PNB Chd CC(PNB,CHD-CC)" },
			{"PNCLA","PNCLA-->PNB CALCUT(CC001)	" },
			{"PNCTA","PNCTA-->PNB CUTTAK(CC890)	" },
			{"PNDWA","PNDWA-->PNB Dws CA(PNB,DEW-CA)" },
			{"PNDWB","PNDWB-->PNB Dws CC(PNB-INDOR-)" },
			{"PNERA","PNERA-->PNB ERNAKU(CC-72)	" },
			{"PNGGA","PNGGA-->PNB Ggn CA(PNB,GUR-CA)" },
			{"PNGGB","PNGGB-->PNB Gurgao(CC0590)	" },
			{"PNGOA","PNGOA-->PNB Panjim(PNB-CC-149)" },
			{"PNGWA","PNGWA-->PNB GUWAHA(CC082)	" },
			{"PNGZA","PNGZA-->PNB GHAZIA(CC-273)	" },
			{"PNINA","PNINA-->PNB Ind CA(PNB,IND-CA)" },
			{"PNINB","PNINB-->PNB Ind CC(PNB,IND-CC)" },
			{"PNINC","PNINC-->PNB Ind CC(PNB,INDOR-)" },
			{"PNJKA","PNJKA-->PNB JAMMU (CC-170)	" },
			{"PNJPA","PNJPA-->PNB JAIPUR(CC-104)	" },
			{"PNLKA","PNLKA-->PNB LUCKNO(CC-1519)	" },
			{"PNMBA","PNMBA-->PNB CC 141(CC-141)	" },
			{"PNMBB","PNMBB-->PNB MUMBAI(CC-22)	" },
			{"PNMBC","PNMBC-->PNB, KURLA(CCAC141)	" },
			{"PNMDA","PNMDA-->PNB MADRAS(CC-069)	" },
			{"PNMOA","PNMOA-->PNB Moh CC(PNB,MOH-CC)" },
			{"PNMRA","PNMRA-->PNB MADURA(CA-775)	" },
			{"PNNDA","PNNDA-->PNB ND CC2(PNB,DEL-CC)" },
			{"PNNDB","PNNDB-->PNB ND CC1(PNB,DEL-CC)" },
			{"PNNDC","PNNDC-->PNB ND CC7(PNB,DEL-CC)" },
			{"PNNDD","PNNDD-->Punjab Nat(PNB-STLOAN)" },
			{"PNNDE","PNNDE-->Punjab Nat(PNB-DDB-00)" },
			{"PNNDF","PNNDF-->Punjab Nat(PNB-DDB-00)" },
			{"PNNDG","PNNDG-->PNB, New D(PNB-PC-INR)" },
			{"PNNDH","PNNDH-->PNB, New D(PNB-PCFC)	" },
			{"PNNDI","PNNDI-->PNB, New D(PNB-FOBP-R)" },
			{"PNNDJ","PNNDJ-->PNB, New D(PNB-FOBP-F)" },
			{"PNNDK","PNNDK-->PNB, New D(PNB-FOBN-R)" },
			{"PNNDL","PNNDL-->PNB, New D(PNB-FOBNF-)" },
			{"PNNDM","PNNDM-->Punjab Nat(PNB-EEFC)	" },
			{"PNNDN","PNNDN-->PNB, New D(PNB-CRYST)	" },
			{"PNNGA","PNNGA-->PNB NAGPUR(CA-356)	" },
			{"PNPNA","PNPNA-->PNB PUNE A(CA-3710)	" },
			{"PNPTA","PNPTA-->PNB PATNA (CC59)	" },
			{"PNPTB","PNPTB-->PNB PATNA (CCNEW)	" },
			{"PNRMA","PNRMA-->PNB Rmjra (PNB,RAILMA)" },
			{"PNRNA","PNRNA-->PNB RANCHI(CC75)	" },
			{"PNRPA","PNRPA-->PNB Rpr CC(PNB,ROPAR-)" },
			{"PNRPB","PNRPB-->PNB PH-1 M(CC-130)	" },
			{"PNRPC","PNRPC-->PNB PH-IV (CA-1484)	" },
			{"PNSCA","PNSCA-->PNB SECUND(CC-860)	" },
			{"PSMOA","PSMOA-->PSB Moh CC(PSB,MOH-CC)" },
			{"PSNDA","PSNDA-->PSB ND CC1(PSB,DEL-CC)" },
			{"PSNDB","PSNDB-->PSB ND CC5(PSB,DEL-CC)" },
			{"PSNDC","PSNDC-->PSB ND CC4(PSB,DEL-CC)" },
			{"PSNDD","PSNDD-->PSB ND CC5(PSB,DEL-CC)" },
			{"PSNDE","PSNDE-->PSB ND CC5(PSB,DEL-CC)" },
			{"PSNDF","PSNDF-->PSB ND CC5(PSB,DEL-CC)" },
			{"PSNDG","PSNDG-->PSB ND CC4(PSB,DEL-CC)" },
			{"PSNDH","PSNDH-->PSB ND CC5(PSB,DEL-CC)" },
			{"PSNDI","PSNDI-->PSB ND CC5(PSB,DEL-CC)" },
			{"PSNDJ","PSNDJ-->Punjab & S(PSB-STLOAN)" },
			{"PSNDK","PSNDK-->Punjab & S(PSB-PC-INR)" },
			{"PSNDL","PSNDL-->Punjab & S(PSB-PCFC)	" },
			{"PSNDM","PSNDM-->Punjab & S(PSB-FOBP-R)" },
			{"PSNDN","PSNDN-->Punjab & S(PSB-FOBP-F)" },
			{"PSNDO","PSNDO-->Punjab & S(PSB-FOBN-R)" },
			{"PSNDP","PSNDP-->Punjab & S(PSB-FOBN-F)" },
			{"PSNDQ","PSNDQ-->Punjab & S(PSB-CRYST)	" },
			{"PSNDR","PSNDR-->PSB ND CC5(CC54)	" },
			{"PSNDS","PSNDS-->Punjab & S(PSB_CC_56)	" },
			{"PSPOA","PSPOA-->PSB Pnt CC(PSB,PAONT-)" },
			{"PSPOB","PSPOB-->PSB Pnt CC(PSB-CC64)	" },
			{"PSPOC","PSPOC-->PUNJAB AND(CA-802)	" },
			{"PSRPA","PSRPA-->PSB Rpr CC(PSB,MOH-CC)" },
			{"SBGOA","SBGOA-->SBI Ponda (CA-0100000)" },
			{"SBMBA","SBMBA-->State Bank(DDB1000062)" },
			{"SBMBB","SBMBB-->SBI Mum CA(SBI,MUMB-C)" },
			{"SBMOA","SBMOA-->SBI Moh CA(SBI,MOH-CA)" },
			{"SBNDA","SBNDA-->SBI ND CA0(SBI,OKH-CA)" },
			{"SBNDB","SBNDB-->SBI ND CA0(SBICA01000)" },
			{"SBNDC","SBNDC-->SBI ND CA1(SBI,OKHLA-)" },
			{"SBNDD","SBNDD-->SBI-FOBP I(SBI-FOBP-I)" },
			{"SBNDE","SBNDE-->SBI-FOBN-F(SBI-FOBP-F)" },
			{"SBNDF","SBNDF-->SBI-FOBN I(SBI-FOBN-I)" },
			{"SBNDG","SBNDG-->SBI FOBN F(SBI-F0BN-F)" },
			{"SBNDH","SBNDH-->SBI New De(CC-0160000)" },
			{"SBPNA","SBPNA-->SBI Saswad(SBI-CA-7/5)" },
			{"SBPOA","SBPOA-->SBI Pnt CA(SBI-CA2095)" },
			{"SCNDA","SCNDA-->SCB ND CA9(STAN-CA-50)" },
			{"SCNDB","SCNDB-->SCB ND CA7(STAN-CA502)" },
			{"SCNDC","SCNDC-->Standard C(STAN-STLOA)" },
			{"SCNDD","SCNDD-->Standard C(STAN-PC-RU)" },
			{"SCNDE","SCNDE-->Standard C(STAN-PCFC)	" },
			{"SCNDF","SCNDF-->Standard C(STAN-FOBP-)" },
			{"SCNDG","SCNDG-->Standard C(STAN-FOBP-)" },
			{"SCNDH","SCNDH-->Standard C(STAN-FOBN-)" },
			{"SCNDI","SCNDI-->Standard C(STAN-FOBN-)" },
			{"SCNDJ","SCNDJ-->Standard C(STAN-CRYST)" },
			{"SGNDA","SGNDA-->Societe Ge(CA-01NKA/0)" },
			{"TRANS","TRANS-->RUPEE TREA(TRANSITION)" },
			{"VJNDA","VJNDA-->VIJAYA ND (VIJAYA-CA2)" }
				       
	};			       
				       
				       
%>				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       
				       